### ISSUE TITLE
What's wrong with my shops.yml? (1st Section - Raiding)

### ISSUE THREAD

**Issue by nagnol** [pablo67340/GUIShop#82] opened 2020-12-03 21:15 UTC
https://pastebin.com/P7S40zEM

**Comment by Skyslycer** [comment] 2021-02-21 00:54
Im not really sure what the problem is, bcs u didnt explain, but here is what i found: u forgot the sections pages:, page0: and items:![Screenshot_20210221-015327_Chrome.jpg](https://user-images.githubusercontent.com/73074974/108612315-be2a1280-73e7-11eb-8d7c-d7413c1bd70d.jpg) i hope that helps

**Comment by Skyslycer** [comment] 2021-02-21 21:46
If that fixed it please close the issue, because we would like to keep the issue section clean.

**Comment by pablo67340** [comment] 2021-02-21 21:49
This is using the old GUIShop shops.yml format. Please delete your shops.yml, update to GUIShop 8.5 and restart your server. Problem will be fixed, and the new format will show itself.

**Closed by pablo67340** 2021-02-21 21:49 UTC
