### ISSUE TITLE
Commands not declared in the plugin.yml file

### ISSUE THREAD

**Issue by DoctorSclero** [pablo67340/GUIShop#40] opened 2020-03-05 09:26 UTC
The commands must be declared in the plugin.yml file or minecraft can't understand the command, please fix, thank's

**Comment by pablo67340** [comment] 2020-03-05 14:57
Minecraft can understand the commands just fine and they all work. You
cannot declare dynamic commands in the plugin yml. The only commands
eligible would be the guishop configuration commands which never change.

**Comment by A248** [comment] 2020-03-19 13:02
GuiShop dynamically provides commands through the PlayerCommandPreProcessEvent. I say *provides* because the commands are not formally *registered*. However, such command logic is not without problems:

- Server owners can't use the commands.yml to define aliases for dynamically-provided commands, because Spigot only recognises aliases which target formally-registered commands from plugin.yml's.
- With normal commands, other plugins can use the PlayerCommandPreProcessEvent to cancel the event, allowing server owners to configure when and where players cannot use a plugin command. E.g., WorldGuard can block commands in a specific WG region. However, this can't be done with GuiShop's dynamically-provided commands.

@pablo67340 , would you consider adding subcommands to the main guishop command? E.g., `/guishop alias buy` and `/guishop alias sell` would be the same as /buy and /sell, provided /buy and sell are the buy-commands and sell-commands configured in the config.yml. Subcommands don't require any registration but they do solve the issues caused by omitting plugin.yml entries for the buy and sell commands.

**Comment by A248** [comment] 2020-03-21 12:02
Fixed by #47 , this issue can be closed now.

**Comment by A248** [comment] 2020-04-19 02:06
There's also an explicit declaration of /guishopuser in the plugin.yml as explained in #55 , in case you weren't satisfied with runtime command registration (although that should ensure command recognisation)

**Closed** 2020-09-24 20:56 UTC
